name: open_cx
description: openCX

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

#agendapp
cloud_firestore: 0.7.3
firebase_admob: 0.5.5
firebase_auth: 0.5.11
google_sign_in: 3.0.4
firebase_analytic: 1.0.1
firebase_core: 0.2.4
firebase_database: 1.0.1
firebase_dynamic_links: 0.02
firebase_messaging: 1.0.2
firebase_performance: 0.0.3
firebase_remote_config: 0.0.4
firebase_storage: 0.3.7

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.5 #guideeasy_app

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  #guideeasy_app
  autocomplete_textfield: ^1.6.4
  sqflite: ^1.1.7+1
  path_provider: ^1.4.0
  flutter_redux: ^0.5.4
  redux_thunk: ^0.2.1
  geolocator: ^5.1.5
  flutter_gherkin: ^1.1.4
  fluttertoast: ^3.1.3
  connectivity: ^0.4.5
  #communio
  html: ^0.13.3+3
  http: ^0.12.0+1
  query_params: '^0.6.1'
  tuple: ^1.0.2
  path: ^1.6.2
  cached_network_image: ^1.1.0
  flutter_svg: ^0.13.1
  synchronized: ^2.1.0
  toast: ^0.1.5
  logger: ^0.7.0+2
  flutter_blue: 0.6.2
  flutter_dotenv: ^2.0.3
  flutter_barcode_scanner: ^0.1.7
  qr_flutter: ^3.1.0
  image_picker:
  #agendapp
  intl: ^0.15.8
  firebase_messaging:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4 #guideeasy_app

#communio
  test: any
  image_test_utils: ^1.0.0
  mockito: 3.0.0

#guideeasy_app
flutter_icons:
  image_path: 'assets/guideasy_app/icon.png'
  android: true
  ios: true
#guideeasy_app


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/guideasy_app/splash_screen/ #guideeasy_app
    - assets/guideasy_app/locations_db/ #guideeasy_app

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/guideasy_app/Pacifico-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/guideasy_app/Roboto-Regular.ttf
        - asset: fonts/guideasy_app/Roboto-Light.ttf
        - asset: fonts/guideasy_app/Roboto-Medium.ttf
        - asset: fonts/guideasy_app/Roboto-Thin.ttf
    - family:  GuideasyIcons
      fonts:
        - asset: fonts/guideasy_app/GuideasyIcons.ttf
    - family: Nunito
      fonts:
        - asset: fonts/communio/Nunito-Black.ttf
          weight: 900
        - asset: fonts/communio/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/communio/Nunito-ExtraBold.ttf
          weight: 800
        - asset: fonts/communio/Nunito-ExtraLight.ttf
          weight: 200
        - asset: fonts/communio/Nunito-Light.ttf
          weight: 300
        - asset: fonts/communio/Nunito-Regular.ttf
          weight: 400
        - asset: fonts/communio/Nunito-SemiBold.ttf
          weight: 600
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
